# Generated by Django 4.2.6 on 2023-10-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threedgame', '0002_alter_ringposition_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cubedata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='move',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ringposition',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
